### ISSUE TITLE
Great project, for instance segmentation?

### ISSUE THREAD

**Issue by Byronnar** [tokudayo/fast-matrix-nms#1]
It can be used for instance segmentation? such as replacing the matrix-nms in SOLOv2, or how to modify it? Thanks

**Comment by tokudayo** [comment]
Hello, it doesn't support instance segmentation as of now. You can modify the CUDA kernel code in `matrix_nms_cuda.cu` to make it work for segmentation. I may try adding the feature if I had time to spare, but in the foreseeable future I'm quite busy

**Comment by Byronnar** [comment]
Ok, Thank you.
